/* c8 ignore start */

export enum Colors {
   BLANC = '#fff',
   BLEU = '#1472bf',
   BLEU_CLAIR = '#4a98d9',
   BLEU_FONCE = '#223654',
   BLEU_MOYEN = '#19406c',
   BLEU_PALE = '#dae6f0',
   BLEU_PIV = '#095797',
   GRIS = '#8893a2',
   GRIS_CLAIR = '#c5cad2',
   GRIS_FONCE = '#4e5662',
   GRIS_MOYEN = '#6b778a',
   GRIS_PALE = '#f1f1f2',
   JAUNE = '#e0ad03',
   JAUNE_FONCE = '#ad781c',
   JAUNE_PALE = '#f8e69a',
   MAUVE = '#6b4fa1',
   NOIR = '#1e1e1e',
   ROSE = '#e58271',
   ROSE_PALE = '#ffdbd6',
   ROUGE = '#cb381f',
   ROUGE_FONCE = '#692519',
   VERT = '#4f813d',
   VERT_FONCE = '#2c4024',
   VERT_PALE = '#d7f0bb',
}

export const theme = {
   dark: false,
   colors: {
      blanc: Colors.BLANC,
      bleu: Colors.BLEU,
      'bleu-clair': Colors.BLEU_CLAIR,
      'bleu-fonce': Colors.BLEU_FONCE,
      'bleu-moyen': Colors.BLEU_MOYEN,
      'bleu-pale': Colors.BLEU_PALE,
      'bleu-piv': Colors.BLEU_PIV,
      gris: Colors.GRIS,
      'gris-clair': Colors.GRIS_CLAIR,
      'gris-fonce': Colors.GRIS_FONCE,
      'gris-moyen': Colors.GRIS_MOYEN,
      'gris-pale': Colors.GRIS_PALE,
      jaune: Colors.JAUNE,
      'jaune-fonce': Colors.JAUNE_FONCE,
      'jaune-pale': Colors.JAUNE_PALE,
      noir: Colors.NOIR,
      rose: Colors.ROSE,
      'rose-pale': Colors.ROSE_PALE,
      rouge: Colors.ROUGE,
      'rouge-fonce': Colors.ROUGE_FONCE,
      vert: Colors.VERT,
      'vert-fonce': Colors.VERT_FONCE,
      'vert-pale': Colors.VERT_PALE,
   },
   variables: {
      'border-color': Colors.GRIS_CLAIR,
      'border-color-focus': Colors.BLEU_CLAIR,
      'border-opacity': 1,
      'link-color': Colors.BLEU,
      'link-color-visited': Colors.MAUVE,
      'link-color-active': Colors.ROUGE,
      'overlay-color': Colors.BLEU_FONCE,
      'overlay-opacity': 0.4,
      'activated-opacity': 0, // NOTE: On mets à 0 pour pouvoir manuellement mettre une couleur spécifique du thème sur les composantes.
   },
};
